"""empty message

Revision ID: fd008321ec51
Revises: a6e89176018b
Create Date: 2020-10-01 10:51:27.489641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd008321ec51'
down_revision = 'a6e89176018b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'name')
    op.drop_column('Show', 'artist_name')
    op.drop_column('Show', 'image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('artist_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('Show', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
